from Rules.RuleH2 import RuleH2
from Rules.RuleH3 import RuleH3
from Rules.RuleS1 import RuleS1
from Rules.RuleS2Max import RuleS2Max
from Rules.RuleS2Min import RuleS2Min
from Rules.RuleS2ShiftMax import RuleS2ShiftMax
from Rules.RuleS2ShiftMin import RuleS2ShiftMin
from Rules.RuleS3Max import RuleS3Max
from Rules.RuleS3Min import RuleS3Min
from Rules.RuleS4 import RuleS4
from Rules.RuleS5 import RuleS5
from Rules.RuleS6Max import RuleS6Max
from Rules.RuleS6Min import RuleS6Min
from Rules.RuleS7 import RuleS7
from Rules.RuleS8RefDay import RuleS8RefDay
from Rules.RuleS8RefShift import RuleS8RefShift
from Rules.RuleS8RefSkill import RuleS8RefSkill
