from strategies.optimiser.generate.rules.Rule0 import Rule0
from strategies.optimiser.generate.rules.Rule1 import Rule1
from strategies.optimiser.generate.rules.Rule2 import Rule2
from strategies.optimiser.generate.rules.Rule3 import Rule3
from strategies.optimiser.generate.rules.Rule4 import Rule4
from strategies.optimiser.generate.rules.Rule5 import Rule5
from strategies.optimiser.generate.rules.Rule6 import Rule6
from strategies.optimiser.generate.rules.Rule7 import Rule7
from strategies.optimiser.generate.rules.Rule8 import Rule8
from strategies.optimiser.generate.rules.Rule9 import Rule9
from strategies.optimiser.generate.rules.Rule10 import Rule10
from strategies.optimiser.generate.rules.Rule11 import Rule11
from strategies.optimiser.generate.rules.Rule12 import Rule12
from strategies.optimiser.generate.rules.Rule13 import Rule13
from strategies.optimiser.generate.rules.Rule14 import Rule14
from strategies.optimiser.generate.rules.Rule15 import Rule15
from strategies.optimiser.generate.rules.Rule16 import Rule16
from strategies.optimiser.generate.rules.Rule17 import Rule17
from strategies.optimiser.generate.rules.Rule18 import Rule18
from strategies.optimiser.generate.rules.Rule19 import Rule19
from strategies.optimiser.generate.rules.Rule20 import Rule20
from strategies.optimiser.generate.rules.Rule21 import Rule21
from strategies.optimiser.generate.rules.Rule22 import Rule22
from strategies.optimiser.generate.rules.Rule23 import Rule23
from strategies.optimiser.generate.rules.Rule24 import Rule24
from strategies.optimiser.generate.rules.Rule25 import Rule25
from strategies.optimiser.generate.rules.Rule26 import Rule26
from strategies.optimiser.generate.rules.Rule27 import Rule27
from strategies.optimiser.generate.rules.Rule28 import Rule28
from strategies.optimiser.generate.rules.Rule29 import Rule29
from strategies.optimiser.generate.rules.Rule30 import Rule30
from strategies.optimiser.generate.rules.Rule31 import Rule31
from strategies.optimiser.generate.rules.Rule32 import Rule32
from strategies.optimiser.generate.rules.Rule33 import Rule33
from strategies.optimiser.generate.rules.Rule34 import Rule34
from strategies.optimiser.generate.rules.Rule35 import Rule35
from strategies.optimiser.generate.rules.Rule36 import Rule36
from strategies.optimiser.generate.rules.Rule37 import Rule37
from strategies.optimiser.generate.rules.Rule38 import Rule38
from strategies.optimiser.generate.rules.Rule39 import Rule39
from strategies.optimiser.generate.rules.Rule40 import Rule40
from strategies.optimiser.generate.rules.Rule41 import Rule41
from strategies.optimiser.generate.rules.Rule42 import Rule42
from strategies.optimiser.generate.rules.Rule43 import Rule43
from strategies.optimiser.generate.rules.Rule44 import Rule44
from strategies.optimiser.generate.rules.Rule45 import Rule45
from strategies.optimiser.generate.rules.Rule46 import Rule46
from strategies.optimiser.generate.rules.Rule47 import Rule47
from strategies.optimiser.generate.rules.Rule48 import Rule48
from strategies.optimiser.generate.rules.Rule49 import Rule49
from strategies.optimiser.generate.rules.Rule50 import Rule50
from strategies.optimiser.generate.rules.Rule51 import Rule51
from strategies.optimiser.generate.rules.Rule52 import Rule52
from strategies.optimiser.generate.rules.Rule53 import Rule53
from strategies.optimiser.generate.rules.Rule54 import Rule54
from strategies.optimiser.generate.rules.Rule55 import Rule55
from strategies.optimiser.generate.rules.Rule56 import Rule56
from strategies.optimiser.generate.rules.Rule57 import Rule57
from strategies.optimiser.generate.rules.Rule58 import Rule58
from strategies.optimiser.generate.rules.Rule59 import Rule59
from strategies.optimiser.generate.rules.Rule60 import Rule60
from strategies.optimiser.generate.rules.Rule61 import Rule61
from strategies.optimiser.generate.rules.Rule62 import Rule62
from strategies.optimiser.generate.rules.Rule63 import Rule63
from strategies.optimiser.generate.rules.Rule64 import Rule64
from strategies.optimiser.generate.rules.Rule65 import Rule65
from strategies.optimiser.generate.rules.Rule66 import Rule66
from strategies.optimiser.generate.rules.Rule67 import Rule67
from strategies.optimiser.generate.rules.Rule68 import Rule68
from strategies.optimiser.generate.rules.Rule69 import Rule69
from strategies.optimiser.generate.rules.Rule70 import Rule70
